version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - broker

  db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sosi
      - POSTGRES_DB=postgres
    volumes:
      - ./schema:/docker-entrypoint-initdb.d 

  broker:
    image: eclipse-mosquitto
    ports:
      - "1886:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_run:/var/run/mosquitto
      #- mosquitto_log:/var/log/mosquitto
      - mosquitto_data:/var/lib/mosquitto
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "#"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      sh -c "mkdir -p /var/run/mosquitto &&
             chown mosquitto:mosquitto /var/run/mosquitto &&
             mosquitto -c /mosquitto/config/mosquitto.conf"
volumes:
  mosquitto_run:
  mosquitto_log:
  mosquitto_data:


